# Generated by Django 4.1 on 2022-10-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_alter_todolistitems_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolistitems',
            name='date',
            field=models.DateField(),
        ),
    ]
